-- Source revisions and normalization versions remain immutable so analysis
-- selections can keep referring to the evidence they actually used.
CREATE TABLE game_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  content_hash TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  headers JSONB NOT NULL DEFAULT '{}'::jsonb,
  header_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  starting_fen TEXT,
  variant TEXT NOT NULL,
  parse_status TEXT NOT NULL CHECK (parse_status IN ('complete','partial','unavailable','unsupported')),
  parse_issues JSONB NOT NULL DEFAULT '[]'::jsonb,
  played_ply_count INTEGER NOT NULL CHECK (played_ply_count >= 0),
  time_control_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(game_id, content_hash, parser_version),
  UNIQUE(game_id, id)
);

ALTER TABLE games ADD COLUMN current_version_id BIGINT;
ALTER TABLE games ADD CONSTRAINT games_current_version_fk
  FOREIGN KEY (id, current_version_id) REFERENCES game_versions(game_id, id)
  DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE game_version_sources (
  version_id BIGINT NOT NULL REFERENCES game_versions(id) ON DELETE CASCADE,
  raw_payload_id BIGINT NOT NULL REFERENCES raw_payloads(id),
  json_pointer TEXT NOT NULL,
  first_seen_at BIGINT NOT NULL,
  PRIMARY KEY(version_id, raw_payload_id, json_pointer)
);
CREATE INDEX idx_game_version_sources_raw ON game_version_sources(raw_payload_id);
CREATE INDEX idx_game_versions_game ON game_versions(game_id, id DESC);

-- Node zero represents the starting position. Every other node represents a
-- move occurrence in a tree; is_mainline distinguishes actual play from RAVs.
CREATE TABLE game_move_nodes (
  version_id BIGINT NOT NULL REFERENCES game_versions(id) ON DELETE CASCADE,
  node_index INTEGER NOT NULL CHECK (node_index >= 0),
  parent_index INTEGER,
  variation_index INTEGER NOT NULL CHECK (variation_index >= 0),
  ply INTEGER NOT NULL CHECK (ply >= 0),
  is_mainline BOOLEAN NOT NULL,
  mover TEXT CHECK (mover IN ('white','black')),
  move_uci TEXT,
  move_san TEXT,
  fen_before TEXT,
  fen_after TEXT,
  position_key_before TEXT,
  position_key_after TEXT,
  comments JSONB NOT NULL DEFAULT '[]'::jsonb,
  starting_comments JSONB NOT NULL DEFAULT '[]'::jsonb,
  nags JSONB NOT NULL DEFAULT '[]'::jsonb,
  annotations JSONB NOT NULL DEFAULT '[]'::jsonb,
  PRIMARY KEY(version_id, node_index),
  FOREIGN KEY(version_id, parent_index) REFERENCES game_move_nodes(version_id, node_index)
    DEFERRABLE INITIALLY DEFERRED,
  CHECK ((node_index = 0 AND parent_index IS NULL AND move_uci IS NULL)
      OR (node_index > 0 AND parent_index IS NOT NULL AND parent_index < node_index))
);
CREATE INDEX idx_game_moves_position ON game_move_nodes(position_key_before, mover)
  WHERE is_mainline AND node_index > 0;

-- Lexical evidence prevents a forgiving chess parser from silently discarding
-- malformed, unknown, duplicate, or reserved PGN elements.
CREATE TABLE game_pgn_tokens (
  version_id BIGINT NOT NULL REFERENCES game_versions(id) ON DELETE CASCADE,
  token_index INTEGER NOT NULL CHECK (token_index >= 0),
  kind TEXT NOT NULL,
  token_text TEXT NOT NULL,
  start_offset INTEGER NOT NULL,
  end_offset INTEGER NOT NULL,
  interpretation_status TEXT NOT NULL CHECK (interpretation_status IN ('parsed','preserved','invalid')),
  PRIMARY KEY(version_id, token_index),
  CHECK (end_offset >= start_offset AND start_offset >= 0)
);

CREATE TABLE game_clock_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL REFERENCES game_versions(id) ON DELETE CASCADE,
  node_index INTEGER,
  kind TEXT NOT NULL CHECK (kind IN ('remaining','elapsed')),
  source TEXT NOT NULL CHECK (source IN ('pgn','provider')),
  source_pointer TEXT NOT NULL,
  raw_text TEXT NOT NULL,
  seconds NUMERIC,
  unit TEXT NOT NULL,
  precision_seconds NUMERIC,
  status TEXT NOT NULL CHECK (status IN ('parsed','invalid','unmapped')),
  reference TEXT NOT NULL CHECK (reference IN ('after_move','elapsed_move','unknown')),
  FOREIGN KEY(version_id,node_index) REFERENCES game_move_nodes(version_id,node_index),
  CHECK ((status = 'parsed' AND seconds IS NOT NULL AND seconds >= 0)
      OR (status IN ('invalid','unmapped'))),
  UNIQUE(version_id, source, source_pointer)
);
CREATE INDEX idx_game_clocks_node ON game_clock_observations(version_id, node_index);

-- Calculations never overwrite provider observations. Inputs and method are
-- explicit so an improved timing algorithm can coexist with prior results.
CREATE TABLE game_derived_timings (
  version_id BIGINT NOT NULL,
  node_index INTEGER NOT NULL,
  method_version TEXT NOT NULL,
  seconds NUMERIC NOT NULL CHECK (seconds >= 0),
  input_observation_ids JSONB NOT NULL,
  assumptions JSONB NOT NULL,
  PRIMARY KEY(version_id, node_index, method_version),
  FOREIGN KEY(version_id,node_index) REFERENCES game_move_nodes(version_id,node_index)
);
