-- Existing inline payloads remain readable until an operator relocates them.
CREATE TABLE archive_objects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backend TEXT NOT NULL CHECK (backend IN ('local', 's3')),
  location TEXT NOT NULL,
  object_key TEXT NOT NULL,
  body_hash TEXT NOT NULL,
  stored_hash TEXT NOT NULL,
  compression TEXT NOT NULL CHECK (compression = 'gzip'),
  body_bytes BIGINT NOT NULL CHECK (body_bytes >= 0),
  stored_bytes BIGINT NOT NULL CHECK (stored_bytes >= 0),
  created_at BIGINT NOT NULL,
  UNIQUE (backend, location, object_key)
);
CREATE INDEX ix_archive_body_identity ON archive_objects(backend, location, body_hash, body_bytes);

ALTER TABLE raw_payloads ALTER COLUMN raw_body DROP NOT NULL;
ALTER TABLE raw_payloads ADD COLUMN archive_object_id BIGINT REFERENCES archive_objects(id);
ALTER TABLE raw_payloads ADD CONSTRAINT raw_payload_body_location
  CHECK ((raw_body IS NOT NULL AND archive_object_id IS NULL)
      OR (raw_body IS NULL AND archive_object_id IS NOT NULL));
CREATE INDEX ix_raw_archive_object ON raw_payloads(archive_object_id);

-- Import evidence is independent of whether parsing subsequently succeeds.
CREATE TABLE archive_imports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_object_id BIGINT NOT NULL REFERENCES archive_objects(id),
  workspace_id TEXT NOT NULL CHECK (length(btrim(workspace_id)) > 0),
  source_name TEXT NOT NULL,
  media_type TEXT NOT NULL,
  captured_at BIGINT NOT NULL
);
CREATE INDEX ix_archive_import_workspace ON archive_imports(workspace_id, id);
