-- Profile bodies are deduplicated; observations retain every successful fetch.
ALTER TABLE raw_payloads ADD COLUMN owner_scope TEXT NOT NULL DEFAULT 'public';
ALTER TABLE fetch_logs ADD COLUMN provider_user_id BIGINT REFERENCES provider_users(id);
CREATE INDEX idx_fetch_log_provider_user ON fetch_logs(provider_user_id, id);
-- A private-only target is an identity placeholder, not a public observation.
-- Its collection dates remain on the scoped acquisition/observation records.
ALTER TABLE provider_users ALTER COLUMN first_seen_at DROP NOT NULL;
ALTER TABLE provider_users ALTER COLUMN updated_at DROP NOT NULL;
-- Historical request captures cannot prove whether OAuth was used, and bodies
-- may be compressed or external. Keep all old Lichess profiles out of public
-- reads until a source replay verifies the absence of caller-relative fields.
UPDATE raw_payloads SET owner_scope = 'unassigned:legacy-profile'
WHERE provider = 'lichess' AND endpoint_type = 'user_profile';
CREATE INDEX idx_raw_payload_owner_scope ON raw_payloads(owner_scope, id);
ALTER TABLE user_snapshots
    ADD COLUMN native_data JSONB,
    ADD COLUMN created_at BIGINT,
    ADD COLUMN last_seen_at BIGINT,
    ADD COLUMN real_name TEXT,
    ADD COLUMN location TEXT,
    ADD COLUMN avatar_url TEXT,
    ADD COLUMN profile_url TEXT,
    ADD COLUMN is_verified BOOLEAN,
    ADD COLUMN is_streamer BOOLEAN,
    ADD COLUMN fide_rating INTEGER;

CREATE TABLE user_rating_records (
    snapshot_id BIGINT NOT NULL REFERENCES user_snapshots(id),
    performance TEXT NOT NULL,
    rating INTEGER,
    best_rating INTEGER,
    best_at BIGINT,
    lowest_rating INTEGER,
    lowest_at BIGINT,
    rating_deviation DOUBLE PRECISION,
    provisional BOOLEAN,
    games INTEGER,
    wins INTEGER,
    losses INTEGER,
    draws INTEGER,
    progress INTEGER,
    native_data JSONB NOT NULL,
    PRIMARY KEY(snapshot_id, performance)
);

CREATE TABLE user_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_user_id BIGINT NOT NULL REFERENCES provider_users(id),
    snapshot_id BIGINT NOT NULL REFERENCES user_snapshots(id),
    raw_payload_id BIGINT NOT NULL REFERENCES raw_payloads(id),
    fetch_log_id BIGINT REFERENCES fetch_logs(id),
    observation_key TEXT NOT NULL UNIQUE,
    captured_at BIGINT NOT NULL,
    endpoint_type TEXT NOT NULL
);
CREATE INDEX idx_user_observations_history ON user_observations(provider_user_id, captured_at DESC, id DESC);
CREATE INDEX idx_user_observations_snapshot ON user_observations(snapshot_id);
CREATE INDEX idx_user_observations_raw_account ON user_observations(raw_payload_id, provider_user_id, captured_at);
INSERT INTO user_observations(provider_user_id, snapshot_id, raw_payload_id,
                             fetch_log_id, observation_key, captured_at, endpoint_type)
SELECT DISTINCT ON(f.id) s.provider_user_id, s.id, f.raw_payload_id, f.id,
       'fetch:' || f.id, f.attempted_at, f.endpoint_type
FROM fetch_logs f
JOIN user_snapshots s ON s.raw_payload_id = f.raw_payload_id
  OR EXISTS(SELECT 1 FROM source_records r WHERE r.entity_type = 'user_snapshot'
            AND r.entity_id = s.id AND r.raw_payload_id = f.raw_payload_id)
WHERE f.status_code IN (200,304)
ORDER BY f.id, s.id DESC;
INSERT INTO user_observations(provider_user_id, snapshot_id, raw_payload_id,
                             observation_key, captured_at, endpoint_type)
SELECT DISTINCT ON(s.raw_payload_id) s.provider_user_id, s.id, s.raw_payload_id,
       'raw:' || s.raw_payload_id, r.fetched_at, r.endpoint_type
FROM user_snapshots s JOIN raw_payloads r ON r.id = s.raw_payload_id
WHERE NOT EXISTS(SELECT 1 FROM fetch_logs f WHERE f.raw_payload_id = s.raw_payload_id AND f.status_code IN (200,304))
ORDER BY s.raw_payload_id, s.id DESC;

CREATE TABLE provider_user_aliases (
    provider_user_id BIGINT NOT NULL REFERENCES provider_users(id),
    username_normalized TEXT NOT NULL,
    display_username TEXT NOT NULL,
    first_seen_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    raw_payload_id BIGINT REFERENCES raw_payloads(id),
    PRIMARY KEY(provider_user_id, username_normalized)
);
CREATE INDEX idx_provider_alias_name ON provider_user_aliases(username_normalized);
INSERT INTO provider_user_aliases(provider_user_id, username_normalized, display_username, first_seen_at, last_seen_at)
SELECT id, username_normalized, display_username, first_seen_at, updated_at FROM provider_users;

CREATE TABLE user_resource_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_user_id BIGINT NOT NULL REFERENCES provider_users(id),
    owner_scope TEXT NOT NULL DEFAULT 'public',
    resource_key TEXT NOT NULL,
    parameters JSONB NOT NULL DEFAULT '{}',
    parameters_hash TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    native_data JSONB NOT NULL,
    coverage_status TEXT NOT NULL CHECK(coverage_status IN ('observed', 'empty', 'partial', 'unknown')),
    coverage_note TEXT,
    parser_version TEXT NOT NULL,
    UNIQUE(provider_user_id, owner_scope, resource_key, parameters_hash, content_hash)
);
CREATE INDEX idx_user_resource_lookup ON user_resource_snapshots(provider_user_id, owner_scope, resource_key, parameters_hash);
CREATE TABLE user_resource_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES user_resource_snapshots(id),
    raw_payload_id BIGINT NOT NULL REFERENCES raw_payloads(id),
    fetch_log_id BIGINT REFERENCES fetch_logs(id),
    observation_key TEXT NOT NULL UNIQUE,
    captured_at BIGINT NOT NULL
);
CREATE INDEX idx_user_resource_observation_history ON user_resource_observations(snapshot_id, captured_at DESC, id DESC);
CREATE INDEX idx_user_resource_observation_raw ON user_resource_observations(raw_payload_id, snapshot_id, captured_at);

CREATE TABLE user_resource_acquisition (
    provider_user_id BIGINT NOT NULL REFERENCES provider_users(id),
    provider TEXT NOT NULL REFERENCES providers(key),
    username_normalized TEXT NOT NULL,
    owner_scope TEXT NOT NULL,
    resource_key TEXT NOT NULL,
    parameters JSONB NOT NULL,
    parameters_hash TEXT NOT NULL,
    source_key TEXT NOT NULL,
    attempted_at BIGINT NOT NULL,
    status_code INTEGER NOT NULL,
    raw_payload_id BIGINT REFERENCES raw_payloads(id),
    PRIMARY KEY(provider_user_id, owner_scope, resource_key, parameters_hash)
);
CREATE INDEX idx_resource_acquisition_username
    ON user_resource_acquisition(provider, username_normalized);

CREATE TABLE rating_history_points (
    snapshot_id BIGINT NOT NULL REFERENCES user_resource_snapshots(id),
    perf_index INTEGER NOT NULL,
    point_index INTEGER NOT NULL,
    performance TEXT NOT NULL,
    rating_date DATE NOT NULL,
    rating INTEGER NOT NULL,
    source_pointer TEXT NOT NULL,
    PRIMARY KEY(snapshot_id, perf_index, point_index)
);
CREATE INDEX idx_rating_history_date ON rating_history_points(performance, rating_date);

-- Future imports/adapters can add providers without rewriting the base schema.
ALTER TABLE providers DROP CONSTRAINT providers_key_check;
