-- Server-owned ceilings and counters survive job delivery, retries, and reruns.
CREATE TABLE work_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  crawl_run_id BIGINT UNIQUE REFERENCES crawl_runs(id),
  standalone_job_id BIGINT UNIQUE REFERENCES discovery_jobs(id),
  policy JSONB NOT NULL,
  remote_requests BIGINT NOT NULL DEFAULT 0 CHECK(remote_requests >= 0),
  remote_bytes BIGINT NOT NULL DEFAULT 0 CHECK(remote_bytes >= 0),
  games BIGINT NOT NULL DEFAULT 0 CHECK(games >= 0),
  normalization_units BIGINT NOT NULL DEFAULT 0 CHECK(normalization_units >= 0),
  exhausted_dimension TEXT,
  exhausted_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CHECK((crawl_run_id IS NULL) <> (standalone_job_id IS NULL))
);
ALTER TABLE crawl_runs ADD COLUMN work_budget_id BIGINT REFERENCES work_budgets(id);
ALTER TABLE discovery_jobs ADD COLUMN work_budget_id BIGINT REFERENCES work_budgets(id);
CREATE INDEX ix_work_budgets_workspace ON work_budgets(workspace_id,id);

CREATE TABLE workspace_budget_periods (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  period_start BIGINT NOT NULL,
  period_end BIGINT NOT NULL,
  remote_requests BIGINT NOT NULL DEFAULT 0 CHECK(remote_requests >= 0),
  remote_bytes BIGINT NOT NULL DEFAULT 0 CHECK(remote_bytes >= 0),
  games BIGINT NOT NULL DEFAULT 0 CHECK(games >= 0),
  normalization_units BIGINT NOT NULL DEFAULT 0 CHECK(normalization_units >= 0),
  PRIMARY KEY(workspace_id,period_start)
);
CREATE TABLE workspace_budget_policies (
  workspace_id TEXT PRIMARY KEY REFERENCES workspaces(id),
  policy JSONB NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE TABLE budget_game_items (
  budget_id BIGINT NOT NULL REFERENCES work_budgets(id),
  game_key TEXT NOT NULL,
  PRIMARY KEY(budget_id,game_key)
);
CREATE TABLE work_request_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id BIGINT NOT NULL REFERENCES work_budgets(id),
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  period_start BIGINT NOT NULL,
  reserved_bytes BIGINT NOT NULL CHECK(reserved_bytes > 0),
  consumed_bytes BIGINT CHECK(consumed_bytes >= 0 AND consumed_bytes <= reserved_bytes),
  created_at BIGINT NOT NULL
);
CREATE TABLE workspace_claim_turns (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  stage TEXT NOT NULL,
  turn BIGINT NOT NULL,
  PRIMARY KEY(workspace_id,stage)
);
CREATE SEQUENCE workspace_claim_turn;

CREATE FUNCTION inherit_work_budget() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.crawl_run_id IS NOT NULL THEN
    SELECT work_budget_id INTO NEW.work_budget_id FROM crawl_runs WHERE id=NEW.crawl_run_id;
  ELSIF NEW.parent_job_id IS NOT NULL THEN
    SELECT work_budget_id INTO NEW.work_budget_id FROM discovery_jobs WHERE id=NEW.parent_job_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER job_work_budget BEFORE INSERT ON discovery_jobs
  FOR EACH ROW EXECUTE FUNCTION inherit_work_budget();
